#include "headfile.h"
extern float Turn_Cam_Center_P_Table[11];
extern float Turn_Cam_Center_D_Table[11];
extern float Turn_Cam_Straight_P_Table[11];
extern float Turn_Cam_Straight_D_Table[11];
extern float Turn_Cam_Center_P;
extern PID PID_CAR_STRAIGHT_CAM;
extern PID PID_CAR_CENTER_CAM;
extern float Mid_slope;
extern float Mid_intercept;
extern float Mid_status;
extern float car_straight_dias;
extern float car_center_dias;
extern float car_diffcomp_dias;
extern float car_center_PWM;
extern float car_diffcomp_PWM;
float car_center(void);
float car_straight(float car_dias);
void Turn_Cam_New(void);
float M_Slope_fig(void);
int gmyshuoqianbuchulai(int temp);
void Center_offset_filter(void);
void Straight_offset_filter(void);
float Car_diff_comp(void);
void Turn_diff_comp(void);
extern float DEBUG_SLOPE;
extern int DEBUG_MIDMAXMIN;